--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    role: myrole
  name: static-web
spec: 
  containers: 
    - 
      image: nginx
      name: web
      ports: 
        - 
          containerPort: 80
          name: web
          protocol: TCP
